# Excluded directories
# exclude = [
#     ".git",
#     ".svn",
#     ".venv",
#     ".vscode",
#     "build",
#     "node_modules",
#     "site-packages",
# ]

# Formatting
line-length = 79
# indent-width = 4

# Python version
# target-version = "py38"

[lint]
# Rules selection
select = [
    # Everything
    # "ALL",
    # pycodestyle (errors)
    "E",
    # pycodestyle (warnings)
    # "W",
    # Pyflakes
    "F",
    # pyupgrade
    # "UP",
    # flake8-bugbear
    # "B",
    # flake8-simplify
    # "SIM",
    # isort
    # "I",
    # McCabe complexity
    # "C90",
    # "C901",
]
# ignore = []

# Fix selection
# fixable = ["ALL"]
# unfixable = []

# Allow unused variables when underscore-prefixed
# dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# [lint.pycodestyle]
# max-line-length = 88
# max-doc-length = 88

[lint.pydocstyle]
convention = "google"

[format]
# Quoting style
# quote-style = "double"

# Indent with spaces or tabs
# indent-style = "space"

# Magic trailing commas
# skip-magic-trailing-comma = false

# Auto-detect line endings
# line-ending = "auto"

# Auto-formatting of code examples in docstrings
# docstring-code-format = false

# Line length limit in docstrings
# docstring-code-line-length = "dynamic"
